### ISSUE TITLE
External point size matrix to heatmaply_cor() fails to produce plot

### ISSUE THREAD

**Issue by rifius** [talgalili/heatmaply#266]
# Describe the bug
When providing a point_size_mat to `heatmaply_cor()`, plotly mode, colormaps fail to be created for points.

# To Reproduce

     # Generate random matrices
     m1 = matrix(rnorm(100), nrow=25, ncol=4, dimnames=list(paste0('Ar', 1:25), paste0('Ac', 1:4)))
     m2 = matrix(rnorm(200), nrow=25, ncol=8, dimnames=list(paste0('Br', 1:25), paste0('Bc', 1:8)))

     # Compute correlations and p-values
     ee = WGCNA::corAndPvalue(m1, m2, use='pairwise.complete.obs', method='spearman')

     # Custom hover info
     hinf = ee$nObs
     hinf[] = paste('n. Obs:', hinf)

     heatmaply::heatmaply_cor(
          ee$cor,
          label_names = c('R', 'C', 'Corr'),
          node_type = 'scatter',
          point_size_mat = -log10(ee$p),
          point_size_name = '-log10(P)',
          dendrogram = adend,
          hclust_method = 'ward.D2',
          custom_hovertext = hinf,
          plot_method = 'plotly'
        )

The plot appears without any dot or color legend (but otherwise complete) with warning message:
        Warning: Ignoring .... observations
        Warning: Didn't find a colorbar to modify.

# Additional context
Debugging  seems to indicate the problem is in `R/plots.R:290-295`, in function `plotly_heatmap()`.
The internal 'melt' redefinition has rownames and colnames swapped in the factors, rendering all melted matrices with NAs

**Comment by Alanocallaghan** [comment]
Doesn't this also have something to do with the fact that the rownames and colnames of the correlation matrix are completely different...?

**Comment by Alanocallaghan** [comment]
Should be resolved 2eb5d9e

**Comment by ImNotaGit** [comment]
@Alanocallaghan It seems that this issue still occurs with the current github version, which I think is [a978eb6](https://github.com/talgalili/heatmaply/commit/a978eb624a144d27ca9407bc6dd28cc2a748d56a). Basically, a part of the plot fails to show up with `node_type="scatter"` and `plot_method="plotly"`. If using the default `plot_method="ggplot"` then everything seems fine.

Example:
```
heatmaply(mtcars, node_type="scatter", point_size_mat=mtcars) # this is OK
heatmaply(mtcars, node_type="scatter", point_size_mat=mtcars, plot_method="plotly") # some rows are blank
```

BTW, currently for me the main reason why I would prefer to use `plot_method="plotly"` is that for custom hovertext,
> if plot_method is "plotly" then just this text is displayed; if plot_method if "ggplot" then it is appended to the existing text.
and I would like to simply replace the default hovertext. Further, I wonder whether it is easy in the next package update to make custom hovertext behave consistently regardless of `plot_method`, and may be have another option specifying whether the custom hovertext should be appended or should replace the default hovertext.

**Comment by Alanocallaghan** [comment]
Good spot, sorry about that! this is fixed on master now

@tal can you push to CRAN? It's a bug that creates incorrect output so fairly urgent

**Comment by Alanocallaghan** [comment]
> Further, I wonder whether it will be easy in the next package update to make the common options work, as well as the custom hovertext behave consistently regardless of plot_method. This is a great package, thank you very much.

I'm not sure I understand what you're asking here? If there's specific things broken or not supported based on plot_method I'm happy to have a look, you can open a separate issue with a list if you like

**Comment by talgalili** [comment]
Thanks for the bug report @rifius 
@Alanocallaghan  - thanks for taking care of it so quickly.
I've tested the latest version on github, and submitted to it CRAN now. I hope it would come through fine within 24 hours.

Cheers,
T

**Comment by ImNotaGit** [comment]
Wow, thank you all for fixing this so quickly!

> > Further, I wonder whether it will be easy in the next package update to make the common options work, as well as the custom hovertext behave consistently regardless of plot_method. This is a great package, thank you very much.
> 
> I'm not sure I understand what you're asking here? If there's specific things broken or not supported based on plot_method I'm happy to have a look, you can open a separate issue with a list if you like

@Alanocallaghan This is indeed a separate issue, and not really a bug. I was just mentioning it as it was related to differences between the two `plot_method`s ("plotly" and "ggplot" ). But if you allow me to elaborate here -- basically, it appears to me that the two methods behave somewhat differently, and some `heatmaply` arguments work for one but not the other, which is not very convenient from the users' standpoint. Examples, as mentioned, include the different ways `custom_hovertext` is displayed, and e.g. `colorbar_len`, `colorbar_thickness` etc. only applies to `plot_method="plotly"`. BTW, I haven't been able to figure out how to change the legend size when `plot_method="ggplot"`. I also just realized that `scale_fill_gradient_fun` only works for `plot_method="ggplot"`, and when using `plot_method="plotly"` I have to use `colors` instead. It would be great if the same arguments can be used to customize elements of the heatmap independent of `plot_method`  -- basically a better, simpler and more consistent "user interface".

**Comment by Alanocallaghan** [comment]
> it appears to me that the two methods behave somewhat differently, and some heatmaply arguments work for one but not the other

Yes, in fact my motivation for add the plotly method was because I found limitations with ggplotly that I couldn't overcome.

Conversely the plotly method could in theory be a superset of the ggplotly method, but there are some very tricky options like (as you note) `scale_fill_gradient_fun`. Using this with plotly would require working with things like translations, limits, breaks, etc, and mapping these to arguments in heatmaply. It's possible but tricky enough that I've not taken the time to work through it.

Again, if there are any specific areas you'd like improved, then please do open an issue detailing them. If it's a general comment that the two are different, the answer is "I know, I don't like it, but it's the best that I could do when implementing those features with limited time".

**Comment by ImNotaGit** [comment]
> Conversely the plotly method could in theory be a superset of the ggplotly method, but there are some very tricky options like (as you note) `scale_fill_gradient_fun`. Using this with plotly would require working with things like translations, limits, breaks, etc, and mapping these to arguments in heatmaply. It's possible but tricky enough that I've not taken the time to work through it.
> 
> Again, if there are any specific areas you'd like improved, then please do open an issue detailing them. If it's a general comment that the two are different, the answer is "I know, I don't like it, but it's the best that I could do when implementing those features with limited time".

Of course, and totally understandable. The color gradient could be an easy "fix" though, but I could be wrong. When I have some time I may try to do a pull request. Thanks again for this wonderful package and your kind help.
